### ISSUE TITLE
Feedback: Output Option

### ISSUE THREAD

**Issue by Shazgul** [zerolx/bingscan#1]
Could you add an Output Option ?
Because if i use `>` function i always get an error:

`python bingscan.py game.php?cat= > out.txt
Remember: If you abuse, bing will ban you IP
Traceback (most recent call last):
  File "bingscan.py", line 19, in <module>
    print link.get_text()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-36: ordinal not in range(128)`

**Comment by zerolx** [comment]
This was an encoding error, already fixed
Thanks for reporting
